### PR TITLE
Make it easier to use together with eglot

### PR DESCRIPTION
**Pull request by skangas**
Without this, and following the advice in the README, I had ruff try to lint my C code. This is obviously not what anyone wants.

I also added a commit that makes flymake-ruff prefer ruff.toml to pyproject.toml if it exists, which is presumably what a user would want.

### CODE REVIEW

**Comment by erickgnavar** [comment]
Hi, thanks for the improvements, could you provide a way to reproduce the issue with C files? I opened a C file and enable `eglot` but I couldn't reproduce the issue

**Review by doolio — COMMENTED** [review]
If the list of config files is in order of precedence then this change is good as from the Ruff docs 
"If Ruff detects multiple configuration files in the same directory, the .ruff.toml file will take precedence over the ruff.toml file, and the ruff.toml file will take precedence over the pyproject.toml file."

**Comment by erickgnavar** [comment]
> Hi, thanks for the improvements, could you provide a way to reproduce the issue with C files? I opened a C file and enable `eglot` but I couldn't reproduce the issue

ping @skangas 

also can you consider what @doolio said about the order of precedence?

**Comment by erickgnavar** [comment]
Closed by inactivity, precedence order of config file was fixed in 165ee1f

**Pull request closed without merging**
